##########################################################################################################
###########################################################################################################
###### [ General ]
# *********************************************************************************************************
###########################################################################################################
spring.profiles.active: "local"
server:
  name: "example"
  port: "8080"


###########################################################################################################
###########################################################################################################
###### [ Management (https://docs.spring.io/spring-boot/docs/current/reference/html/actuator.html) ]
# *********************************************************************************************************
###########################################################################################################
management:
  server:
    port: "9080"
  endpoints:
    web:
      exposure:
        #include: [ "health" ]
        include: "*"
  health:
    livenessState:
      enabled: "true"
    readinessState:
      enabled: "true"
    diskSpace:
      enable: "true"
  endpoint:
    health:
      enabled: "true"
      show-details: "always"


###########################################################################################################
###########################################################################################################
###### [ Spring-boot ]
# *********************************************************************************************************
#  https://docs.spring.io/spring-boot/docs/current/reference/html/application-properties.html
###########################################################################################################
spring:
  application:
    name: "MyApplication"
  main:
    allow-circular-references: "false"

###########################################################################################################
###########################################################################################################
###### [ My application settings ]
###########################################################################################################
application:
  load-info:
    enabled: true